### ISSUE TITLE
superalgos does not start

### ISSUE THREAD

**Issue by Wotan666** [Superalgos/Platform#124]
Hi everyone, 

can someone help me I can't get it to start.

Web Server Started.
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::1337
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at Server.setupListenHandle [as _listen2] (net.js:1355:14)
    at listenInCluster (net.js:1396:12)
    at Server.listen (net.js:1480:7)
    at startHtttpServer (E:\Downloads\Tradingprogram\WebServer\server.js:47:56)
    at Object.<anonymous> (E:\Downloads\Tradingprogram\WebServer\server.js:40:1)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
Events Server Started.
Web Socket Server Started.
Task Manager Server Started.

**Comment by Luis-Fernando-Molina** [comment]
Hi, thank you for reporting this. What is happening is that Superalgos Web Server cannot be started. The reason is that the port number is trying to use is already in use by another application. The web server cannot be started until either you stop the other application or you change the port number at the WebServer/.env file for an unused one. (variable name VIRTUAL_PORT). This can also happen if you run the command to start the app 2 times in different consoles, one of them took the port and the second one displays this error. I dont think this is your case. Just change the port number please at the configuration .ENV file.

For the next version, I promise the app will show a clear message of what is going on.

**Comment by Luis-Fernando-Molina** [comment]
Sorry the .ENV file to modify is the one at the root directory, not at the webServer folder.

**Comment by Wotan666** [comment]
Thank you very much... I will test it tonight

**Comment by Wotan666** [comment]
great it work´s
